# Optional Lab: Python, NumPy and Vectorization

A brief introduction to some of the scientific computing used in this course. In particular the NumPy scientific computing package and its use with Python

In [1]:
import numpy as np
import time

## Vectors

### Vector Creation

Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

In [5]:
# NumPy routines which allocate memory and fill arrays with value

a = np.zeros(4);                print(f"np.zeros(4):    a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,):   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4):    a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,):   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.60507543 0.82686125 0.98468259 0.47130105], a shape = (4,), a data type = float64


In [15]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument

a = np.arange(4.);                  print(f"np.arange(4.):   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);              print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype})")

np.arange(4.):   a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.87687541 0.97771779 0.76645003 0.08274166], a shape = (4,), a data type = float64)


In [18]:
a = np.array([5,4,3,2]);    print(f"np.array([5,4,3,2])  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]);   print(f"np.array([5.,4,3,2])  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2])  a = [5 4 3 2], a shape = (4,), a data type = int32
np.array([5.,4,3,2])  a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


### Operations on Vectors

#### Indexing

In [21]:
# vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

# access an element
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")

try:
    c = a[10]
except Exception as e:
    print(f"Error: {e}")

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accessing an element returns a scalar
a[-1] = 9
Error: index 10 is out of bounds for axis 0 with size 10


#### Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [29]:
a = np.arange(10)

c = a[2:7:1];   print(f"a[2:7:1] = {c}")

c = a[2:7:2];   print(f"a[2:7:2] = {c}")

c = a[3:];      print(f"a[3:]: {c}")

c = a[:3];      print(f"a[:3]: {c}")

c = a[:];       print(f"a[:3]: {c}")

a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:]: [3 4 5 6 7 8 9]
a[:3]: [0 1 2]
a[:3]: [0 1 2 3 4 5 6 7 8 9]


#### Single vector operations

In [34]:
a = np.array([1,2,3,4])

# negate elements of a
b = -a
print(f"b = -a: {b}")

b = np.sum(a)
print(f"b = np.sum(a): {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2: {b}")

b = -a: [-1 -2 -3 -4]
b = np.sum(a): 10
b = np.mean(a): 2.5
b = a**2: [ 1  4  9 16]


#### Vector Vector element-wise operations

In [36]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(f"Binary operators work element wise: {a + b}")

c = np.array([1,2])

try:
    d = a + c
except Exception as e:
    print(f"Error: {e}")

Binary operators work element wise: [0 0 6 8]
Error: operands could not be broadcast together with shapes (4,) (2,) 


#### Scalar Vector operations

In [37]:
a = np.array([1,2,3,4])

b = 5 * a
print(f"b = 5 * a: {b}")

b = 5 * a: [ 5 10 15 20]


#### Vector Vector dot product

![alt text](images/C1_W2_Lab04_dot_notrans.gif "Title")

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

In [39]:
def my_dot(a, b):
    """
    Compute the dot product of two arrays
    :param a: 
    :param b: 
    :return: 
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [41]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4 ,3 ,2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [42]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4 ,3 ,2])
c = np.dot(a, b)
print(f"np.dot(a, b) = {c}")
c = np.dot(b, a)
print(f"np.dot(b, a) = {c}")

np.dot(a, b) = 24
np.dot(b, a) = 24


In [43]:
np.random.seed(1)
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)

tic = time.time()  # capture start time
c = np.dot(a, b)
toc = time.time()  # capture end time

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del a
del b  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 28.3377 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 1976.5058 ms 


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

#### Vector Vector operations in Course 1

In [47]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")


X[1] has shape (1,)
w has shape (1,)
c has shape ()


## Matrices

![alt text](images/C1_W2_Lab04_Matrices.png "Title")

### Matrix Creation

In [55]:
a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1, 1))
print(f"a shape = {a.shape}, a = {a}")


a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [59]:
a = np.array([[5],[4],[3]]);        print(f"a shape = {a.shape}, a = {a}")
a = np.array([[5],
              [4],
              [3]])
print(f"a shape = {a.shape} a = {a}")

a shape = (3, 1), a = [[5]
 [4]
 [3]]
a shape = (3, 1) a = [[5]
 [4]
 [3]]


### Operations on Matrices

#### Indexing

Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column.

In [65]:
a = np.arange(6).reshape(-1, 2)
print(f"a.shape: {a.shape}, \na = {a}")

# access an element
print(f"\na[2,0].shape: {a[2,0].shape}, a[2,0] = {a[2,0]}")

# access a row
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}")

a.shape: (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4
a[2].shape: (2,), a[2] = [4 5]


#### Slicing

In [73]:
a = np.arange(20).reshape(-1, 10)
print(a)

# access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1])

# access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1])

# access all elements
print("a[:,:] = \n", a[:,:])

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:])

print("a[1] = ", a[1])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6]
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]]
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[1,:] =  [10 11 12 13 14 15 16 17 18 19]
a[1] =  [10 11 12 13 14 15 16 17 18 19]
